#!/bin/sh

# if there's a gh-pages tree and it matches master:dist/app,
# then get out now, there's nothing to do:

current=`git rev-parse -q --verify gh-pages:` \
&& test $current = "`git rev-parse -q --verify master:dist/app`" \
&& exit 0

# update the gh-pages ref to a new commit ...    
git update-ref refs/heads/gh-pages $(
    # ... which has master:dist/app, parented on gh-pages if that exists yet
    git commit-tree ${current:+-p gh-pages} -m "updating" master:dist/app
)
